### ISSUE TITLE
Cannot Save Config

### ISSUE THREAD

**Issue by iangoh414** [klaviyo/magento2-klaviyo#1]
Under Store->Catalog->Catalog-> save Config
Under Store->Catalog->XML Sitemap-> save Config

You will get the error “Something went wrong while saving this configuration: We Can’t save the cron expression.”

Please help to fix this asap

**Comment by henry-chan-klaviyo** [comment]
This issue has been triaged and it looks to be that our observer is listening on too generic of a submit event causing issues with saving settings outside of our extension settings. As a work around, the version of the extension from the Magento Marketplace is in a good state.

You'll first need to uninstall this version with composer before installing the Magento Marketplace version. The differences between this version and the Magento Marketplace version is that this version allows for the ability to restore abandoned carts as well as syncing Klaviyo lists.

**Comment by henrylamchan** [comment]
Fixed on master here
