### ISSUE TITLE
Product Delete not Working after install Module

### ISSUE THREAD

**Issue by alep93** [klaviyo/magento2-klaviyo#105]
If i comment this:
Klaviyo\Reclaim\Observer\ProductDeleteBefore 
Product delete working fine.

The issue is on: 
public function execute(Observer $observer)
    {
        $product = $observer->getEvent()->getProduct();
        $websiteIds = $product->getWebsiteIds();
        $storeIdKlaviyoMap = $this->_klaviyoScopeSetting->getStoreIdKlaviyoAccountSetMap($websiteIds);

        foreach ($storeIdKlaviyoMap as $klaviyoId => $storeIds) {
            if (empty($storeIds)) {
                continue;
            }

            if ($this->_klaviyoScopeSetting->getWebhookSecret() && $this->_klaviyoScopeSetting->getProductDeleteBeforeSetting($storeIds[0])) {
                $data = array (
                    'store_ids' => $storeIds,
                    'product_id' => $product->getId(),
                );
                $this->_webhookHelper->makeWebhookRequest('product/delete', $data, $klaviyoId);
            }
        }
    }

to => $storeIdKlaviyoMap = $this->_klaviyoScopeSetting->getStoreIdKlaviyoAccountSetMap($websiteIds);

**Comment by remstone7** [comment]
Thanks for bringing this up, we're currently working on a fix for this!
