### ISSUE TITLE
3.0.3 tag is missing

### ISSUE THREAD

**Issue by ihor-sviziev** [klaviyo/magento2-klaviyo#114]
Right now in the [changelog ](https://github.com/klaviyo/magento2-klaviyo/blob/master/CHANGELOG.md)and on the [Magento marketplace](https://marketplace.magento.com/klaviyo-magento2-extension.html) we can see that latest version is 3.0.3, but the tag isn't available.
![image](https://user-images.githubusercontent.com/1873745/120438999-b08f0c00-c38a-11eb-826c-d3c3206f90eb.png)
![image](https://user-images.githubusercontent.com/1873745/120439048-bbe23780-c38a-11eb-9488-454f22df31a9.png)

https://github.com/klaviyo/magento2-klaviyo/compare/3.0.2...3.0.3 shows no diff at all right now, the https://github.com/klaviyo/magento2-klaviyo/releases shows 3.0.2 as well.
![image](https://user-images.githubusercontent.com/1873745/120438858-863d4e80-c38a-11eb-9d65-ee56fe56fa1c.png)
![image](https://user-images.githubusercontent.com/1873745/120439097-cd2b4400-c38a-11eb-8435-6890ae7f6e18.png)

@klaviyojad @remstone7 Could you fix that?

**Comment by klaviyojad** [comment]
@ihor-sviziev apologies as was waiting for the extension to passed the Marketplace automated testing and manual Q/A.  It should be set now.

**Comment by ihor-sviziev** [comment]
Yeah, now it's there. I'm closing this issue.
Thx for a quick fix!
