### ISSUE TITLE
SMS Consent for Registered Customers with Saved Addresses

### ISSUE THREAD

**Issue by mpchadwick** [klaviyo/magento2-klaviyo#135]
The SMS consent feature adds a checkbox to the shipping address form.

For registered customers with saved addresses, the checkbox will not be available if checking out with an existing saved address. This seems to be a serios gap in the functionality.

Is Klaviyo planning to address this use case as part of the module. Our client wants to make sure this use case is covered if they enable this functionality. We can custom build the something, but if Klaviyo is going to add it (it seems like you should) we'd just need to discard our code later, which would be a waste of time.

**Comment by klaviyojad** [comment]
@mpchadwick thank you for bringing it to our attention.  I am sorry that we missed that scenario when we first developed the feature.  I was able to test locally and can confirm what you are seeing.  I have opened an internal ticket with our team to fix this issue.  Will update here as well once we have a solution which will come in the form of an update to our extension

**Comment by mpchadwick** [comment]
@klaviyojad - Great thanks. Do you have any sense of timeline for when this functionality would be available?

**Comment by klaviyojad** [comment]
@mpchadwick not yet until we figure out the solution.  So far I have been able to detect when this occurs but trying to find a way to get the checkbox displayed in the Knockout JS when default shipping is set for the registered users

**Comment by klaviyojad** [comment]
@mpchadwick we have a [PR](https://github.com/klaviyo/magento2-klaviyo/pull/138) out for review to solve this issue. 
Sorry it took so long but UI changes like this always require approval from Product Managers and Legal before proceeding
