### ISSUE TITLE
Track Profile Activity Use Deprecated Request

### ISSUE THREAD

**Issue by pmclain** [klaviyo/magento2-klaviyo#146]
https://github.com/klaviyo/magento2-klaviyo/blob/688b85ea27649ef0a4e56f0f4e6edcd5d020e09c/Helper/Data.php#L131

The track events are using an encoded `GET` request which fails for larger payloads. I don't know the exact length but beyond a certain size Klaviyo rejects the events with `414 Request-URI Too Large`. Klaviyo's API docs recommend sending the track event using the `POST` method.

https://apidocs.klaviyo.com/reference/track-identify#track-get

![image](https://user-images.githubusercontent.com/12674247/141333650-5147a7df-e1b1-48ad-8ff9-f35d351e2930.png)

**Comment by cykolln** [comment]
Thank you for pointing this out, this has been added to our roadmap.

**Comment by cykolln** [comment]
This was fixed in release 4.0.2
