### ISSUE TITLE
Klaviyo overrides saveShippingInformation JS action and removes other extension attributes

### ISSUE THREAD

**Issue by kamilszewczyk** [klaviyo/magento2-klaviyo#148]
We have noticed, that once we installed Klaviyo module, our other 3rd party module Amasty Delivery Date have stopped working as the fields for delivery date and comments have not been passed to PHP.
After investigation it turned out, that Klaviyo module rebuild the saveShippingInformation payload disregarding any other information that could be inserted in the extension_attributes section of payload.

The issue comes from: Klaviyo_Reclaim::js/model/shipping-save-processor/default.js

**Comment by klaviyojad** [comment]
@kamilszewczyk could you please share what version of Magento 2 is your system and what version of the Klaviyo Extension you have installed when you saw this?

**Comment by kamilszewczyk** [comment]
@klaviyojad - your comment lead me to check release notes and I can see the issue has actually been fixed. Sorry for bothering!
