### ISSUE TITLE
Message: Property "2" does not have accessor method "get2" in class "Magento\Quote\Api\Data\AddressExtensionInterface". {"exception":"[object]

### ISSUE THREAD

**Issue by GreaterDiktakis** [klaviyo/magento2-klaviyo#153]
Just installed module version 3.0.10 on Magento 2.4.1

After enabling and configuring the "Consent and Checkout", this causes 500 error for shipping-information API call (moving from Shipping Step to Payment Step)

**Comment by klaviyojad** [comment]
@GreaterDiktakis I work for the Support Engineers and will be happy to take a look at this for you.  Does this not happen if you do not set consent?  Either case, could please file an email support ticket as described [here](https://help.klaviyo.com/hc/en-us/articles/115001002272-How-to-Contact-Support#email-support1) so we can try to troubleshoot?

**Comment by GreaterDiktakis** [comment]
Hey @klaviyojad 

It occurs regardless of if you click on the consent or not. Only way for this to be fixed is for the configuration to be disabled (for Consent Checkbox).

However, the client has decided not to go with Klaviyo and therefore I can't follow up further on this.
