### ISSUE TITLE
ACL is missing

### ISSUE THREAD

**Issue by mortenbirkelund** [klaviyo/magento2-klaviyo#160]
The module is missing ACL, meaning that only admin users with full access is able to see the module.

**Comment by mortenbirkelund** [comment]
https://devdocs.magento.com/guides/v2.4/ext-best-practices/tutorials/create-access-control-list-rule.html

**Comment by klaviyojad** [comment]
@mortenbirkelund thank you for bringing this to our attention.  This has been brought up [here](https://github.com/klaviyo/magento2-klaviyo/issues/98) and is currently in our backlog

**Comment by mortenbirkelund** [comment]
Thanks. Do you think this will ever get fixed?

**Comment by klaviyojad** [comment]
@mortenbirkelund like I said, its in our backlog.  Its not really a blocker for many customers just a nice to have.

**Comment by JamesFX2** [comment]
oh ffs

**Comment by snoop0x7b** [comment]
> @mortenbirkelund like I said, its in our backlog. Its not really a blocker for many customers just a nice to have.

PCI does require that you give people the least possible level of permissions to do their job. https://pcidssguide.com/pci-dss-requirement-7/

**Comment by cykolln** [comment]
Thanks for the contribution @snoop0x7b! This has been merged and is available in the latest release
