### ISSUE TITLE
question: compatibility with magento 2.2.7

### ISSUE THREAD

**Issue by akosglue** [klaviyo/magento2-klaviyo#167]
which version can we install for magento ce 2.2.7?

**Comment by klaviyojad** [comment]
@akosglue have you tried installing version 3.0.4 from https://packagist.org/packages/klaviyo/magento2-extension#3.0.4 ?
you can install it by running `composer require klaviyo/magento2-extension:3.0.4`

**Comment by akosglue** [comment]
yes, but it didn't succeed.
for example:
klaviyo/magento2-extension 3.0.4 requires magento/module-quote >=101.1.0 <=101.1.3
klaviyo/magento2-extension 3.0.0 requires magento/module-quote >=101.1.0

finally the installed version is: ^2 (2.2.0)

thanks for the advice, it goes with version 2.
