### ISSUE TITLE
Private API Key Stored in plain text

### ISSUE THREAD

**Issue by pmclain** [klaviyo/magento2-klaviyo#18]
https://github.com/klaviyo/magento2-klaviyo/blob/master/etc/adminhtml/system.xml#L21-L23
Should this be an obscure config value instead of text?

**Comment by Pr00xxy** [comment]
Also consider using the `Encrypted` backend model 
`<backend_model>Magento\Config\Model\Config\Backend\Encrypted</backend_model>`
together with `Magento\Framework\Encryption\EncryptorInterface::decrypt()` when accessing value

**Comment by njparadis** [comment]
Hey guys, this is being addressed in PR #54: https://github.com/klaviyo/magento2-klaviyo/pull/54/files#diff-c4a53edec4557757b0db215231c89c32R21
