### ISSUE TITLE
Lack of indexType on DB indexes

### ISSUE THREAD

**Issue by valenciaisaza** [klaviyo/magento2-klaviyo#188]
https://github.com/klaviyo/magento2-klaviyo/blob/158140087d0ea29533ca59c59d927d35f0a49f76/etc/db_schema.xml#L16

add the `indexType="btree"` to the db_schema.xml to avoid bin/magento setup:upgrade error

This is for all 4 index in that file for versions > 4.0.0

**Note**: This problem is when use PHP8 for the last magento version 2.4.4

**Comment by svalveson** [comment]
We are having the same issue here

**Comment by gabriel3iri** [comment]
I was trying to update this extension and got this exact problem, setup:upgrade doesn't work and found this problem with the index, I'm using PHP 8.1

**Comment by cykolln** [comment]
Closing this issue out (duplicate: https://github.com/klaviyo/magento2-klaviyo/issues/185). This is a known issue and will be fixed in the next release.
