### ISSUE TITLE
Wrong parameter names in PHPDoc for productinspector() method

### ISSUE THREAD

**Issue by lepiklepik** [klaviyo/magento2-klaviyo#199]
hey guys,

you have wrong PHPDoc parameter names in the productinspector() method at https://github.com/klaviyo/magento2-klaviyo/blob/01f101d2138aa4c5879b6e0863f1ec8c0b11db23/Api/ReclaimInterface.php#L80

**Comment by jorgb90** [comment]
Yes! This breaks SOAP API!

**Comment by cykolln** [comment]
Thanks for reporting this issue, we have merged the fix and it will be included in the next release.

**Comment by smoucka** [comment]
Fixed in https://github.com/klaviyo/magento2-klaviyo/pull/207
