### ISSUE TITLE
Cannot save Theme Configuration

### ISSUE THREAD

**Issue by iangoh414** [klaviyo/magento2-klaviyo#2]
Content->Configuration-> Edit (Theme) ->Save Configuration, you will get an error.

Something went wrong while saving this configuration: Notice: Undefined index: field in /home/vocando/public_html/store/vendor/klaviyo/magento2-extension/Observer/PrivateApiKeyObserver.php on line 25

Please fix this ASAP

**Comment by henry-chan-klaviyo** [comment]
This is a duplicate of https://github.com/klaviyo/magento2-klaviyo/issues/1
