### ISSUE TITLE
Add to cart breaks on PHP 8

### ISSUE THREAD

**Issue by edas11** [klaviyo/magento2-klaviyo#201]
Hello,

On Magento 2.4.4 (PHP 8) we get this error when adding a product which doesn't have any images to the cart:
`report.CRITICAL: Exception: Deprecated Functionality: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/klaviyo/magento2-extension/Observer/SalesQuoteProductAddAfter.php on line 75 in vendor/magento/framework/App/ErrorHandler.php:61`

Could you fix this error?

**Comment by cykolln** [comment]
This fix has been merged, will update here once the release has gone out

**Comment by cykolln** [comment]
This has been fixed as of the latest release 4.0.7
