### ISSUE TITLE
 Klaviyo\Reclaim\Cron\EventsTopic::deleteMovedRows does not exist 

### ISSUE THREAD

**Issue by rafaelstz** [klaviyo/magento2-klaviyo#250]
### Environment details

PHP version: 8.1.13
Magento version: 2.4.5-p2 Commerce
Klaviyo extension version: 4.0.7

### Steps to reproduce

1. Have Klaviyo integrate
2. Install Magerun 2
3. Run `php -d memory_limit=-1 ./var/n98-magerun2.phar sys:cron:run`
4. Type the number that represent the cron **klaviyo_events_cleanup** from the list

### Expected result

Run the events cleanup without error

### Actual result

This error below has been returned from manual or scheduled execution.

<img width="656" alt="Klaviyo\Reclaim\Cron\EventsTopic::deleteMovedRows does not exist" src="https://user-images.githubusercontent.com/610598/234096524-f4aa3c9c-b956-448a-bcbd-dfcfc259fd19.png">

**Comment by cykolln** [comment]
Please update to at least extension version 4.0.8 - this was fixed in the next version.
