### ISSUE TITLE
Invalid Support Mail Address

### ISSUE THREAD

**Issue by sprankhub** [klaviyo/magento2-klaviyo#270]
### Description

As shown in the [README](https://github.com/klaviyo/magento2-klaviyo#support), I contacted support via extensions@klaviyo.com. However, this e-mail address seems to be no longer valid - I got an error reply.

**Comment by cykolln** [comment]
Hi, thanks for bringing this to our attention. Sorry about that! We are working on getting this email back up and running - in the meantime you can contact support: https://help.klaviyo.com/hc/en-us/articles/115001002272

**Comment by cykolln** [comment]
Thanks for raising - this has been fixed!
