### ISSUE TITLE
Error when accessing Klaviyo Newsletter in Configuration

### ISSUE THREAD

**Issue by nix0x00** [klaviyo/magento2-klaviyo#277]
### Environment details

PHP version: 7.4
Magento version: 2.4.3-p3
Klaviyo extension version: 4.1.0
Anything else that would help a developer reproduce the bug?

<img width="1424" alt="Screenshot 2023-12-01 at 1 18 48 AM" src="https://github.com/klaviyo/magento2-klaviyo/assets/20900900/ed2ad966-5fdb-43d2-b644-abb04864a19e">

### Steps to reproduce

1. Install Klaviyo 4.1.0
2. setup:upgrade & s:d:c
3. deploy static-content
4. Enter the API public and private keys in Stores > Configuration > Klaviyo
5. Access Newsletter from Stores > Configuration Klaviyo > Newsletter

### Expected result

Should have shown the newsletter configuration, however throws an error.

### Actual result

On frontend or browser following error occurs.

> <style>.highlighted { background-color: #DFF7FF!important; }</style>
> 

     <form action="https://www.domain.com/admin/admin/system_config/save/key/4b62758f04d5d27e9d4c8e2976f1ed799566f8a7c45ebd71edb795bbc908fbd6/section/klaviyo_reclaim_newsletter/" method="post" id="config-edit-form"
      enctype="multipart/form-data">
    <div><input name="form_key" type="hidden" value="zXFYWHBrbhW3Sc2K" /></div>
    <div class="accordion">
        An error has happened during application run. See exception log for details.

### Additional information

Klaviyo 4.1.0 is not working, and recently 4.0.x version stopped working and integration was not being established with Klaviyo. upon contacting support they asked to upgrade the version to 4.1.0. however, 4.1.0 is causing this error.

**Comment by nix0x00** [comment]
> Hey, would you mind sharing your klaviyo public key? [[docs](https://developers.klaviyo.com/en/docs/retrieve_api_credentials#:~:text=Klaviyo%20uses%20public%20and%20private,under%20the%20API%20Keys%20tab.)]

Hey, sure it's `RiPczu`.

**Comment by jordanleslie** [comment]
We were able to recreate this by entering an invalid private api key into the general config section of the klaviyo settings. 
We're going to throw up a fix for this but in the meantime please check that you're using a valid private api key. That should resolve the issue.

**Comment by cykolln** [comment]
This has been merged and the fix is in the latest release!
