### ISSUE TITLE
Shopping Cart Infinite Reloading

### ISSUE THREAD

**Issue by CalzaFino** [klaviyo/magento2-klaviyo#292]
### Environment details

PHP version: 8.2
Magento version: 2.4.6-p4
Klaviyo extension version: Latest

### Steps to reproduce

Add any product to the cart
Go to Shopping Cart page

### Expected result

Shopping Cart page loading and remains “estable”

### Actual result

Shopping Cart page keeps reloading infinitely until user closes it or navigate out of it. 

### Additional information

Disabling the extension in Magento Admin stops the reloading issue.

**Comment by jordanleslie** [comment]
Hey, I'm going to route you over to the support team. [Here's the link to contact them.](https://help.klaviyo.com/hc/en-us/articles/115001002272).

We'll keep this issue open here in case support escalates the issue but please close if you're able to get this resolved with the support team.

**Comment by kamidzi-klaviyo-integrations** [comment]
@CalzaFino  - were you able to resolve this?

**Comment by CalzaFino** [comment]
> @CalzaFino - were you able to resolve this?

In my case, the problem was related to a compatibility issue with the module Breeze by Swissuplabs. They released an update with the fix. Now it is working fine.

**Comment by cykolln** [comment]
@CalzaFino Thanks for the update! Closing this one out!
