### ISSUE TITLE
E-Mail not encoded in searchProfileByEmail

### ISSUE THREAD

**Issue by spicyavocadooo** [klaviyo/magento2-klaviyo#295]
### Environment details

PHP version: 8.1
Magento version: 2.4.6-p4
Klaviyo extension version: 4.1.3
Anything else that would help a developer reproduce the bug?

### Steps to reproduce

Create customer with email address including "+" symbol
Unsubscribe Customer
Subscribe Customer again

### Expected result

Customer is subscribed to newsletter after subscribing again

### Actual result

Customer is not subscribed to newsletter after subscribing again, exception in log 
"Unable to subscribe ... to list ...: Klaviyo\Reclaim\KlaviyoV3Sdk\Exception\KlaviyoApiException: A profile already exists with one of these identifiers."

### Additional information

searchProfileByEmail is using normal email and not encoded email as necessary for the API

**Comment by cykolln** [comment]
Thanks for opening - we need to add `urlencode` around the email in `searchProfileByEmail`. We've added this to our backlog and can include it in our next release

**Comment by cykolln** [comment]
This has been fixed in 4.1.4
