### ISSUE TITLE
Swagger is not working

### ISSUE THREAD

**Issue by aurelienchl** [klaviyo/magento2-klaviyo#32]
We're on Magento 2.2.6 and this plugin is causing an error for Swagger. Here's the issue when trying to access to this page:
/rest/all/schema?services=all
Data type "anyType" is not declared.

**Comment by remstone7** [comment]
thanks for bringing that up.. fixing it w/ this https://github.com/klaviyo/magento2-klaviyo/pull/34 `@return mixed[]`

**Comment by remstone7** [comment]
released!
