### ISSUE TITLE
Email address not validated before saving to quote

### ISSUE THREAD

**Issue by jasuten** [klaviyo/magento2-klaviyo#33]
The automatic email address capture on the checkout page is not validated before saving it to the quote, this causes validation issues elsewhere:

Steps to reproduce:
- Add products to cart
- Proceed to checkout page
- Enter malformed email, e.g. example@broken
- Go back to cart page
- Remove a product from cart
- Error message appears "We can't remove the item."

**Comment by remstone7** [comment]
taking a look at this, thanks!

**Comment by remstone7** [comment]
can reproduce, will patch

**Comment by remstone7** [comment]
fixing in https://github.com/klaviyo/magento2-klaviyo/pull/34
