### ISSUE TITLE
Js error _learnq is not defined

### ISSUE THREAD

**Issue by cdiacon-img** [klaviyo/magento2-klaviyo#42]
I suppose this commit introduced changed and breaks the js for the product viewed 
```
ReferenceError: _learnq is not defined
```
https://github.com/klaviyo/magento2-klaviyo/commit/4d7c9370220df81409cb19a257ef77262a1a2245

klaviyo version : 1.1.0
magento : 2.3.2

**Comment by remstone7** [comment]
@cdiacon-img just waiting for a review and will push a patch for version 1.1.1 https://github.com/klaviyo/magento2-klaviyo/pull/41

**Comment by remstone7** [comment]
@cdiacon-img all set, in the new release V1.1.1

**Comment by cdiacon-img** [comment]
@remstone7 thanks for a quick reply, upgrading now... 🎉

**Comment by cdiacon-img** [comment]
@remstone7 just my 2cents here
https://github.com/klaviyo/magento2-klaviyo/commit/7335b5215148a6ea0d1db88ea3d6124a24172b2c

I think this could be done better using require js 
```
define(['domReady!'], function () {
    console.info(' DOM is ready !');
});
```

**Comment by cdiacon-img** [comment]
@remstone7 
I don't think this fixed the issue 😞 

![Screen Shot 2019-07-30 at 6 26 38 PM](https://user-images.githubusercontent.com/48591835/62142799-a071f580-b2f7-11e9-9362-e03a4379fa9b.png)
![Screen Shot 2019-07-30 at 6 26 30 PM](https://user-images.githubusercontent.com/48591835/62142817-a536a980-b2f7-11e9-85de-aeaf6a915de6.png)

**Comment by remstone7** [comment]
hmm alright, will go the requirejs approach, locally tested and looked good for me adding this.
