### ISSUE TITLE
Multistore products need to be passed with the correct store view name

### ISSUE THREAD

**Issue by albsa** [klaviyo/magento2-klaviyo#58]
Hi,

The event data that is passed to klaviyo does not contains the store view name, therefore it is taking the default values, this causes a lot issues in the flows when the incorrect titles are shown.

Please fix this.

**Comment by remstone7** [comment]
Hi, could you be more specific on what event you're referring to?

**Comment by albsa** [comment]
Hi @remstone7 ,
actually all events.
None of the events are passed the right product information according to the current store ID / store view.

All the information that is passed to the klaviyo events are based on the base store version details.
Also the product feeds in klaviyo does not fetch the correct store ID product information, all is based on the base store view information.

Do you understand what I mean?

**Comment by remstone7** [comment]
@albsa we do use the store_id for the query to fetch products for our catalog, as well as our order data (these queries are all store scoped).  Would you be able to write into our support to show examples from the catalog of this in the product feed as this is all done via our rest api integration and not our extension? Please do so following these steps https://help.klaviyo.com/hc/en-us/articles/115001002272-How-to-Contact-Support and someone from the team will be able to help investigate exactly what you see

The only thing that would be an event coming from the extension (this GH repo) would be the viewed product metric which the call to get the current product information is https://github.com/klaviyo/magento2-klaviyo/blob/19e71b06eb6f5b9744d9846b47a16483aadfa061/Block/Catalog/Product/ViewedProduct.php#L81 and using the registry looks like best practice for this.

**Comment by albsa** [comment]
HI @remstone7,

Just got a bunch of e-mail tickets that you got asigned.
I think you already found me. It is the email of kidsluxury.

Let's communicate from there.

**Comment by remstone7** [comment]
great, i think there was a delay in processing our support form that just got resolved this morning.  We will chat over email, thanks for the recommendations and comments here!
