### ISSUE TITLE
Warning message Fallback to JQueryUI Compat activated

### ISSUE THREAD

**Issue by jasuten** [klaviyo/magento2-klaviyo#78]
We are getting the following console warning on the checkout:

`Fallback to JQueryUI Compat activated. Your store is missing a dependency for a jQueryUI widget. Identifying and addressing the dependency will drastically improve the performance of your site. Compat.js
`

It looks like the file vendor/klaviyo/magento2-extension/view/frontend/web/js/view/checkout/email.js is requiring 'jquery/ui' which causes this warning. It results in all jquery-ui modules being loaded onto the page.

**Comment by ihor-sviziev** [comment]
This issue was fixed in https://github.com/klaviyo/magento2-klaviyo/pull/83.
I think we can mark this issue as fixed.
