### ISSUE TITLE
Doesn't work with 2.4 due to 2FA

### ISSUE THREAD

**Issue by webamondo** [klaviyo/magento2-klaviyo#80]
Currently when you try to integrate Klaviyo with Magento 2.4 you are unable to connect due to 2FA. The only work around is to disable the 2FA module.

**Comment by remstone7** [comment]
Hi @webamondo that is correct - we're will be working on a different authentication pattern this month/next month to handle the changes for 2.4

**Comment by remstone7** [comment]
@webamondo we're working on this and will most likely be completed in December (will follow up here) - the only workaround we have to offer is to disable 2FA module

**Comment by lagunacellar** [comment]
Is there any update on this topic?  We were told completion was likely in December 2020.

**Comment by klaviyojad** [comment]
@lagunacellar it is being actively being worked on right now.  We don't have a timeline of expected completion date as of this moment but will keep you posted once we know more.

**Comment by jorgb90** [comment]
Wow this lets me even completely cross out Klaviyo as option..

**Comment by remstone7** [comment]
Hey all, we're still working on this and are just about to wrap up phase 2 of 3 on this project.  This will be released in March, it's a high priority on our end and constantly being worked on.  I'll update here more frequently on the status of the project as we continue to progress.

**Comment by asherrard** [comment]
having this same issue with the current version.
ideally, the solution utilizes magento2 API integrations rather than generating a token via a username/password API token generation for the integration. https://devdocs.magento.com/guides/v2.4/get-started/authentication/gs-authentication-token.html

**Comment by klaviyojad** [comment]
@asherrard we are currently working on an update that uses the OAuth1 integration like you mentioned.  Thanks for you pointing it out, we will keep you posted on once it is released.

**Comment by jorgb90** [comment]
What on earth is taking so long? This issue is raised in October last year..

**Comment by jorgb90** [comment]
@remstone7 Update?

**Comment by remstone7** [comment]
@jorgb90 We are working on releasing this in beta hopefully towards the end of next week, if you want to reach out to our support to let them know you want to be part of the beta we can add your account to it

**Comment by remstone7** [comment]
Hi all, we have this in beta right now.  If you're interested in turning this on, please reach out to our support team to enable it for you.  Otherwise, it will be released fully in the coming weeks https://help.klaviyo.com/hc/en-us/articles/115001002272-How-to-Contact-Support

**Comment by husseycoding** [comment]
Did this change make it live?
