### ISSUE TITLE
Insufficient CSP whitelisting for connect-src and img-src

### ISSUE THREAD

**Issue by zaximus84** [klaviyo/magento2-klaviyo#82]
When visiting the storefront, there are Content Security Policy violations for these files:

(XHR) https://fast.a.klaviyo.com/onsite/api/v2/modules?company_id={company id}

(Image) https://a.klaviyo.com/api/track?data={data}&company_id={company id}&i=1

It looks like more coverage needs to be added to csp_whitelist.xml. I was able to fix it with a patch that adds the following entries:

`
<policy id="connect-src">
    <values>
        <value id="klaviyo-cdn" type="host">https://fast.a.klaviyo.com</value>
    </values>
</policy>
<policy id="img-src">
    <values>
        <value id="klaviyo" type="host">https://a.klaviyo.com</value>
    </values>
</policy>
`

**Comment by remstone7** [comment]
Thank you for pointing this out - we will take a look at this and patch

**Comment by remstone7** [comment]
https://github.com/klaviyo/magento2-klaviyo/pull/87

**Comment by njparadis** [comment]
Released with version 2.0.0
