### ISSUE TITLE
No ACL rules

### ISSUE THREAD

**Issue by vseager** [klaviyo/magento2-klaviyo#98]
There are no ACL rules so that config access cannot be granted to individual user roles:

https://devdocs.magento.com/guides/v2.4/ext-best-practices/tutorials/create-access-control-list-rule.html

**Comment by klaviyojad** [comment]
Hi @vseager below are ACLs you can configure that would satisfy all the api requirements from Klaviyo:

"Catalog > Inventory > Categories",
"Carts > Manage Carts",
"Customers > Customer Groups",
"Customers > All Customers",
"Sales > Operations > Orders > Actions > View"
"Stores > Attributes > Product",
"Catalog > Inventory > Products"
"Sales > Operations > Shipments"
"Stores > Settings > All Stores"
"Marketing > Communications > Newsletter Subscribers"

**Comment by vseager** [comment]
@klaviyojad I wasn't referring to the API requirements but the settings in `Stores > Settings > Configuration`. At the moment there is no way to control access to Klaviyo configuration for different user roles (`System > Permissions > User Roles`).

![klaviyo](https://user-images.githubusercontent.com/2035088/109030342-9e327180-76bb-11eb-9179-da0783b1b79d.png)

![klaviyo2](https://user-images.githubusercontent.com/2035088/109030783-04b78f80-76bc-11eb-83ee-da6001734f1e.png)

**Comment by klaviyojad** [comment]
@vseager you are correct that we currently do not define any new ACLs for access to the Klaviyo extension config as well as new klaviyo endpoints.  Its something we'll have to add to the roadmap

**Comment by vseager** [comment]
@klaviyojad do you have an update on this issue?

**Comment by klaviyojad** [comment]
@vseager again its on the roadmap.  Nothing we are working on currently.  Is it blocking you from anything?

**Comment by cykolln** [comment]
This feature request has been added to the roadmap - closing because it is not an issue

**Comment by vseager** [comment]
@cykolln Was this fixed? There is still no `/etc/acl.xml` in the repo?

**Comment by cykolln** [comment]
> @cykolln Was this fixed? There is still no `/etc/acl.xml` in the repo?

We created a feature request for this issue and added it to our roadmap. When it gets picked up, a member of the team will follow up.

**Comment by vseager** [comment]
@cykolln Any change of getting this fixed? It really is a 5 minute change?!

**Comment by mortenbirkelund** [comment]
Still nothing?

**Comment by kasperth** [comment]
@cykolln @klaviyojad when do you reckon this will be looked into? as vseager wrote, it's a small change.
